### ISSUE TITLE
Set up Rails project

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#1]
Ruby version: 2.1.5
Rails version: 4.2.2
Database: Postgresql

**Comment by ariaru** [comment]
Database default at first

**Comment by ariaru** [comment]
@ariaru will be there by your side on Sunday - most probably, I'll really try I promise <3

**Comment by Powerglove** [comment]
ok :)

**Comment by joecorcoran** [comment]
https://gist.github.com/joecorcoran/d70631780fb5ef3fbb43 :)

**Comment by ariaru** [comment]
Postgresql:
For Ubuntu, type in the terminal:
sudo apt-get install postgresql libpq-dev

**Comment by joecorcoran** [comment]
[Postgresql setup!](https://gist.github.com/joecorcoran/02217948fa1e80d26b56)

**Comment by ariaru** [comment]
Great work, thanks everyone <3

**Comment by Powerglove** [comment]
Hello,

the Windows installer works so far, but I have questions concerning the setup: Do insert the commands in the shell, that comes with PostgreSQL? If yes, then Windows might need different commands than Mac, as those don't seem to work.

Thanks!

**Comment by joecorcoran** [comment]
Hey Johanna, I just updated the Gist to make it clearer, hope it helps:

https://gist.github.com/joecorcoran/02217948fa1e80d26b56

Joe Corcoran corcoran.io





On Thu, Jul 16, 2015, at 02:29 PM, Johanna Lang wrote:
> Hello,


> the Windows installer works so far, but I have questions concerning
> the setup: Do insert the commands in the shell, that comes with
> PostgreSQL? If yes, then Windows might need different commands than
> Mac, as those don't seem to work.


> Thanks!


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/rubymonsters/diversity_ticketing/issues/1#issuecomment-121943199
