### ISSUE TITLE
Get the app ready to use mid-January for sign ups

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#111]
DRAFT - editing in progress. 

As I've written in the Slack channel, it would be great if we could use the app for applications coming in Mid-January for Craft Conf. The Deadline for Applications would be End of January, the Selection has to be done End of February.

What we would need working Mid-January:
### The sign up: That people can apply for an event
- [x] The form including the questions 
- [x] Some kind of notification after submitting the form 

What we would need working Mid of February:
### The Selection
- [x] admins need to be able to discard applications
- [ ] maybe even sort the applications

What we would need working End of February:
### The Notification
- [ ] admins need to be able to email applicants in bulks (confirmations and declines)

**Comment by lisbethmarianne** [comment]
hi anika, can i aks what exactly means sorting of the application? what would you sort for?

**Comment by lisbethmarianne** [comment]
I guess, we would need something that would mark the application as accepted, something to distinguish when you send the confirmations/declines. How would that look like? Something like the approval of the events (here you can mark them as approved/unapproved). Or do you have something else in mind?

**Comment by lisbethmarianne** [comment]
@lislis @bioshrimp and CSS Team: If you could work on the pages, that are facing the public that would be great. (home, Events: index, show, preview, Applications: new) :kissing_heart:

**Comment by saltinejustine** [comment]
The CSS team can now find design/css information in issue #114 :)

**Comment by anikalindtner** [comment]
@lisbethmarianne the sorting can probably wait for now. (I was thinking being able to sort after e.g. timestamps). We'll see what/ if we need something like this after the first usecase i guess. 

for declining/ accepting an application: We need two steps for this I'd imagine: First, to mark something as declined and then have these declined applications hidden from view so that we can sort through the remaining ones. Second step is to being able to accept an application (which will be the winners). In the end we should have access to three lists: declined, accepted (winners) and all others I guess.

**Comment by fidothe** [comment]
I am closing this because I think you totes did this 😻
