### ISSUE TITLE
Design and CSS for application

### ISSUE THREAD

**Issue by saltinejustine** [rubymonsters/diversity_ticketing#114]
### Design Update / Implementation of Design

Hey all! For those of you in the slack channel, you've seen some designs come in periodically. @anikalindtner and @lislis have access to an application called InVision we use internally at Travis, however we have a cap on how many people can use the app per our current plan. So here I'll post the design mockups as well as what @lislis and I call, "Hot Pink CSS" where I mark up a bunch of CSS suggestions and information for her to see. At first it looks a bit messy but usually does the trick when we can't use InVision.
### Mockups for Screens

![diversityticketing-1](https://cloud.githubusercontent.com/assets/823381/12155258/4b58b1fe-b492-11e5-80b5-e030afa1bba2.png)

![diversityticketing-2](https://cloud.githubusercontent.com/assets/823381/12155264/4b7d0900-b492-11e5-8d65-12778a1069dc.png)

![diversityticketing-3](https://cloud.githubusercontent.com/assets/823381/12155261/4b731d50-b492-11e5-8fe7-a9565d880c59.png)

![diversityticketing-4](https://cloud.githubusercontent.com/assets/823381/12155263/4b7a1326-b492-11e5-9b13-4e1063b09b83.png)

![diversityticketing-5](https://cloud.githubusercontent.com/assets/823381/12155260/4b709e90-b492-11e5-94bc-6043ea1f6f8f.png)

![diversityticketing-6](https://cloud.githubusercontent.com/assets/823381/12155262/4b75431e-b492-11e5-8539-9a28e2da40cb.png)

![diversityticketing-7](https://cloud.githubusercontent.com/assets/823381/12155259/4b6847fe-b492-11e5-9678-19107f06bdb4.png)

![diversityticketing-8](https://cloud.githubusercontent.com/assets/823381/12155265/4b7da96e-b492-11e5-9957-ee9d1a2bc27c.png)
### Hot Pink CSS for Screens

![diversityticketing-hotpinkcss-1](https://cloud.githubusercontent.com/assets/823381/12155290/61eaa88c-b492-11e5-8a5f-c42e8b5ba0b2.png)

![diversityticketing-hotpinkcss-2](https://cloud.githubusercontent.com/assets/823381/12155297/6208dc94-b492-11e5-9a65-4720b5abec33.png)

![diversityticketing-hotpinkcss-3](https://cloud.githubusercontent.com/assets/823381/12155292/61fb39c2-b492-11e5-9a68-28a89866848f.png)

![diversityticketing-hotpinkcss-4](https://cloud.githubusercontent.com/assets/823381/12155293/62020e5a-b492-11e5-885e-71fc7ec129e6.png)

![diversityticketing-hotpinkcss-5](https://cloud.githubusercontent.com/assets/823381/12155294/620305f8-b492-11e5-8963-2c34d749ee85.png)

![diversityticketing-hotpinkcss-6](https://cloud.githubusercontent.com/assets/823381/12155295/6206aaf0-b492-11e5-92e7-dae1e81874e3.png)

![diversityticketing-hotpinkcss-7](https://cloud.githubusercontent.com/assets/823381/12155291/61f7ee52-b492-11e5-8270-f89e27870aa0.png)

![diversityticketing-hotpinkcss-8](https://cloud.githubusercontent.com/assets/823381/12155296/6208a418-b492-11e5-8777-4178f8a6df6a.png)

If you have any questions or concerns, ping me! :sparkles:

**Comment by saltinejustine** [comment]
@lislis the icons/logo are in the invision project asset folder. But only you have access to that. Not sure how you want to share them with others.

**Comment by alicetragedy** [comment]
Love the Hot Pink CSS @saltinejustine <3

**Comment by saltinejustine** [comment]
@alicetragedy it's actually pretty funny, we started doing this _before_ we moved over to invision and to our surprise, guess what color they used?? :P

**Comment by alicetragedy** [comment]
@saltinejustine Hot Pink is the color of pros. :tophat:

**Comment by svenfuchs** [comment]
@saltinejustine WOHAAAAAHHHH :heart: :heart: :heart: :heart: :heart:

**Comment by joecorcoran** [comment]
This is looking amazing. Really excited to see so much activity on this project – I can't wait to share the finished product with everyone! :100:

**Comment by lislis** [comment]
here are some animation prototypes: 
http://codepen.io/lislis/pen/JGNjYG
http://codepen.io/saltinejustine/pen/XXRrow

**Comment by saltinejustine** [comment]
@lislis can this issue be closed now? Seems like Diversity Tickets' design is pretty well finished? 💃

**Comment by lislis** [comment]
I believe so
