### ISSUE TITLE
Make nice texts for emails

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#117]
Email after submitting an event:

Subject: You submitted a new event.
Body: Thank you for submitting your event <%= @event.name %>

Email after submitting an application:

Subject: Thanks for applying for #{@application.event.name}.
Body: Thank you for applying to attend <%= @application.event.name %>!

**Comment by ariaru** [comment]
This is done now for applications, except for the date(s) of the conference.

**Comment by lisbethmarianne** [comment]
Applicants body now:

Dear Katrina,

thank you for applying for a diversity ticket for Monsters Conf in Berlin.

We will contact you after the applications are closed and when the winners of the diversity tickets are raffled out. This might take a couple of weeks.

If you have further questions, you can reach us at foundation@travis-ci.org

We cross our fingers for you,

The Travis Foundation Team

—

**Comment by alicetragedy** [comment]
Looks good! :+1:

**Comment by lisbethmarianne** [comment]
@alicetragedy and @anikalindtner There is no decent text in the email for organizers after submitting an event. Not sure if we need this for the first event. (Will you make this event by yourself?)

Do we need any other emails?

**Comment by lisbethmarianne** [comment]
The Email after submitting an event is also discussed in #60. We ignored that.

So the text could be:

"Dear 'organizer_name',

Thank you for submitting your event 'event-name'. 

Your event is not yet visible to the public. You will be informed as soon as your event is approved. 

If you have any more questions, please read the FAQ (link to FAQ). If you need more help, contact foundation@travis-ci.org.

The Travis Foundation Team

—"

Only problem: FAQ don't exist yet.
And we need another email, informing the organizer that the event is approved.

**Comment by alicetragedy** [comment]
sorry for the delay @lisbethmarianne! To answer all your questions:

- We will create the first event ourselves; so in theory the organiser emails are not strictly needed (however if all you need is content to have them ready, I can help you with that!)
- The only other email needed is the event approval to the organiser. I will post a possible text as a separate comment below.  
- This last email sounds good. regarding the FAQ, do you think we could set up a static page for now, and write a "coming soon" as placeholder? If that's too complicated or not ideal from the user perspective, you can remove that line and just have the email address for now.

**Comment by alicetragedy** [comment]
I just realised that a submitter attendee following a link tweeted out by a conference organiser might not understand what the diversity app is really about, so I think that FAQs (or an About page at the very least) might be needed (see my comment above). I'd be very much up for creating content for this if it can help (and add it in a pull request once a static `about` or `faq` page is created rather than putting it into a comment if that's easier!).
Let me know what you think @lisbethmarianne @anikalindtner

**Comment by anikalindtner** [comment]
@alicetragedy 500% yes on the about/faq page! i'd love it if you could draft something, happy to give feedback then.

**Comment by alicetragedy** [comment]
Text for email of event approval:


Dear 'organiser_name', 
Your event `event_title` has been approved on diversitytickets.org and is now visible to the public. You can view it here: `event_url_in_app`. As of now, applicants can apply for diversity tickets by clicking on the "Apply" link and filling out the form.

If you have any more questions, please read the FAQ (link to FAQ). If you need more help, contact foundation@travis-ci.org.

The Travis Foundation Team

**Comment by lisbethmarianne** [comment]
@alicetragedy See #156
