### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/diversity_ticketing#12]
We need validations for events and applications.

See here being a preparation for next Monday (August, 24):
http://guides.rubyonrails.org/active_record_validations.html

**Comment by lisbethmarianne** [comment]
Haha, we had the same thought at the same minute. :D

**Comment by sabrina-ulbrich** [comment]
Yeah, I remember the homework, when I saw your activity :)) so I close this one. You have a better description :+1:
