### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#120]
... so people can collaborate with us!
:tada:

**Comment by ferbsx** [comment]
http://choosealicense.com

@svenfuch : Which one do you suggest we use? :blush:

**Comment by svenfuchs** [comment]
We usually use MIT for everything :)

**Comment by fidothe** [comment]
I'd probably go with MIT for this :steam_locomotive:

**Comment by fidothe** [comment]
Closed by #122
