### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#13]
Read http://guides.rubyonrails.org/active_record_validations.html

We need validations for Event and Application. So that the forms are not accepted empty or with things that are not an email or a date. 

Event: Organizer name, Organizer email, Description, Name, Start date and End date 
(I guess not all 3 questions have to be there. Maybe an organizer doesn't need questions.)

Application: Name, Email
(Depending on the questions answers should also not be empty. )

Everybody is invited to work on this issue. Pick either event or application and make a new branch while working on the problem. And leave a comment here, if you'd like to work on it.

**Comment by joecorcoran** [comment]
We could consider this gem for validating dates: https://github.com/codegram/date_validator

**Comment by joecorcoran** [comment]
https://github.com/rubymonsters/diversity_ticketing/pull/14 :tada:
