### ISSUE TITLE
[UI] fix padding on notice after logging in

### ISSUE THREAD

**Issue by alicetragedy** [rubymonsters/diversity_ticketing#133]
Haven't noticed this anywhere else for now, but the notice after logging into the app could do with a bit of padding on the left (see screenshot)

<img width="1046" alt="screen shot 2016-01-18 at 17 07 46" src="https://cloud.githubusercontent.com/assets/3143348/12396200/79eded2c-be06-11e5-9f46-6a40ae8d9937.png">

**Comment by lislis** [comment]
good catch! Not sure if we should make the flash messages go full width of not and then either put padding or not. @saltinejustine ping

**Comment by alicetragedy** [comment]
:+1:

**Comment by saltinejustine** [comment]
OH HALLO! 

I think something like this would be good for success alerts

<img width="1147" alt="screen shot 2016-01-18 at 11 41 49 am" src="https://cloud.githubusercontent.com/assets/823381/12397032/8fd2201e-bdd8-11e5-9368-b65a99253943.png">

**Comment by saltinejustine** [comment]
Success check mark icon color: `#c2e1bc`
Success icon container background: `#4f994f`
Success text container background: `#66be66`

**Comment by saltinejustine** [comment]
@lislis Is that cool with y'all?

**Comment by lislis** [comment]
@saltinejustine :dope:

**Comment by saltinejustine** [comment]
![dope](https://media.giphy.com/media/xTiTnufTw66LSnj7kQ/giphy.gif)
