### ISSUE TITLE
[UI] Align terms and conditions line with checkbox

### ISSUE THREAD

**Issue by alicetragedy** [rubymonsters/diversity_ticketing#135]
When applying to a conference, the checkbox for the Terms and Conditions is not aligned with the text (see screenshot).

<img width="381" alt="screen shot 2016-01-18 at 17 35 32" src="https://cloud.githubusercontent.com/assets/3143348/12396867/11a1fea8-be0a-11e5-93a2-433a51e30bd3.png">

**Comment by lisbethmarianne** [comment]
![bildschirmfoto 2016-01-19 um 00 03 42](https://cloud.githubusercontent.com/assets/11691539/12404972/7eec5d2e-be40-11e5-8328-3e0e6edcf061.png)

sorry folks, there are still problems with that. It is fine when you click appy. But when you submit the application with an error, it is not aligned.

**Comment by lislis** [comment]
I believe this can be closed now?

**Comment by lisbethmarianne** [comment]
Still happening for me. (Chrome, Firefox, Safari)
