### ISSUE TITLE
[UI] improve view for list of applications

### ISSUE THREAD

**Issue by alicetragedy** [rubymonsters/diversity_ticketing#136]
in the `admin` area, when viewing the list of applications currently available for a certain event, the bullet points look a bit off, I guess the styling of the rows should be improved so it looks more like a table :) 

<img width="1016" alt="screen shot 2016-01-18 at 17 57 47" src="https://cloud.githubusercontent.com/assets/3143348/12397445/804a48a8-be0d-11e5-8db9-8e5c21017077.png">

**Comment by lislis** [comment]
this still needs to be done. The focus was user first, admin later

**Comment by alicetragedy** [comment]
@lislis totally understandable :+1:  I figured I would just write this down somewhere as something I noticed so it doesn't get lost. And totally agree that it's not something urgent or that needs doing asap!
