### ISSUE TITLE
moar design

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#147]
Heyhey @saltinejustine!

We need some more design :sparkles: please!
![screen shot 2016-01-18 at 21 42 47](https://cloud.githubusercontent.com/assets/1006478/12402358/afc6572e-be2c-11e5-9219-a79a85383940.png)
There is a list of applicants. Always **name**, **email**, **delete**.

![screen shot 2016-01-18 at 21 43 26](https://cloud.githubusercontent.com/assets/1006478/12402357/afc399c6-be2c-11e5-8709-b3b7e75d5cfe.png)
There is a footer now. We just made up some text to fit in the links and there will be more like CoC and help. But maybe you can already think of something nice :)

**Comment by saltinejustine** [comment]
@lislis hej hej hej!!!

For the applicants list:

![diversityticketing-applicants-list-10](https://cloud.githubusercontent.com/assets/823381/12402773/28864f82-bdfd-11e5-86f9-aa118b2fe370.png)

**Comment by saltinejustine** [comment]
@lislis for the footer:

![diversityticketing-footer-09](https://cloud.githubusercontent.com/assets/823381/12403189/68d7d6c0-be00-11e5-8333-67750ae613fa.png)

![diversityticketing-footer-07](https://cloud.githubusercontent.com/assets/823381/12403193/6d9af0ca-be00-11e5-87cd-d869854b216d.png)

**Comment by saltinejustine** [comment]
The icons are now in the invision project :heart: :thought_balloon:

**Comment by lislis** [comment]
@saltinejustine thank youuuuu!

**Comment by lislis** [comment]
I think we're done with this! See the PR https://github.com/rubymonsters/diversity_ticketing/pull/181
