### ISSUE TITLE
[important] adding info field in event submission form 

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#159]
Next to "number of available diversity tickets" in the section "Application Details", we'd need an Info field where we can describe the details of this particular event. 

Background to this: Laura and I need to create 3 different "events" that ppl can apply to for craft conf:

+ diversity ticket
+ diversity ticket + EU grant
+ diversity ticket + Non-EU grant 

That's why we need some additional info to describe the specific details of the event. (In longer term, we need to rethink the structure of "events" (maybe having "subevents" or sth), because all conferences will have different set ups, but this can be discussed later. Just fyi :) )

**Comment by anikalindtner** [comment]
Deadline for this would be *tomorrow, 2nd of February*. If that's too spontanous, please ping @alicetragedy, she could also implement this or help with that.

**Comment by lisbethmarianne** [comment]
@anikalindtner Hm, I think I don't understand this. Can you not use the description for this?

If you are going for the 3 different events, I guess we have to kill the checkbox for travel grants in the application form?

**Comment by anikalindtner** [comment]
@lisbethmarianne yes, we have to kill the checkbox for travel grants. and no we can't use the description for this, because that's only the description of the conf which only shows up in the index page, but not in the appliation form anymore. we need a text that shows up here:

![screen shot 2016-02-01 at 16 06 35](https://cloud.githubusercontent.com/assets/1711357/12721095/453a8df8-c8fe-11e5-9c01-831c14ce694b.png)

**Comment by lisbethmarianne** [comment]
@anikalindtner Can we put the description in the "Detail xyz" place or do you want a totally different text to be there?

**Comment by alicetragedy** [comment]
@lisbethmarianne it should be a different text, something like a subheading or "notice", just probably just a one-liner with important information relevant to the application itself (for example: "travel grant for travelling within EU only").
