### ISSUE TITLE
[UI] add Markdown for usage in the Events description

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#161]
For now you can't style the events description and I'd LOVE to have the possibility to use Markdown, so that these texts can be a bit more styled. 

![screen shot 2016-02-01 at 16 34 35](https://cloud.githubusercontent.com/assets/1711357/12721814/e61e955e-c901-11e5-8509-55ca387573a8.png)

**Comment by alicetragedy** [comment]
I think the most important things are line breaks/paragraphs and minor formatting (bold/italic).

**Comment by anikalindtner** [comment]
yepp yepp yepp!

**Comment by lisbethmarianne** [comment]
There it is. :)
