### ISSUE TITLE
Update Terms & Conditions

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#174]
We need to add a paragraph about reimbursements:

If you applied for a travel grant and were accepted, you will get reimbursed for your costs either up to 300 € (EU) or up to 900 € (non-EU). Note: You will only get reimbursed when the organizers of the conference can confirm that  you actually attended the conference. They will take note of your name at the registration desk.W

**Comment by lisbethmarianne** [comment]
This is important information. What about the costs for tickets?

Problem: I don't think people read terms and conditions. Also they will never remember at the time they get accepted.

Should we also add it to the email, they will get after applying?
