### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#19]
figure out how to implement this

**Comment by joecorcoran** [comment]
Some reading!

* http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Basic.html
* http://berk.es/2011/03/29/simplest-authentication-in-rails-basic-authentication-with-a-logged_in-helper/

**Comment by lisbethmarianne** [comment]
some thoughts:

Possibility to distinguish approved events from non-approved (make new column in database)

Admin_index page: approved / non approved (checkbox?)

not visible to public: admin_index, applications show, pages to show all applications for one event (not yet there)
