### ISSUE TITLE
Rough concept sketch for web forms

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#2]
![img_4799](https://cloud.githubusercontent.com/assets/2119496/8544017/e6ad73c8-24a1-11e5-968b-18ac476f4eea.JPG)

**Comment by ariaru** [comment]
New Decision:
Application model instead of Applicant model!
No Organizer model, instead only Event model!

**Comment by Powerglove** [comment]
Linking the two models: 
one event -> many applicants
primary key = identifies appl. as belonging to a certain event
