### ISSUE TITLE
Approve new Events

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#20]
Possibility to distinguish approved events from non-approved (make new column in database)

Admin_index page: approved / non approved (checkbox?)

**Comment by lisbethmarianne** [comment]
I'd like to work on this. Friday or Saturday. Is somebody joining me (@Powerglove)? Maybe at betahaus?

**Comment by lisbethmarianne** [comment]
@Powerglove I found the problem. The line validates :organizer_email_confirmation, presence: true in the event model prevented the update action. I deleted it now. Creating a new event by leaving the confirmation field blank doesn't work, so it seems fine. But we should check it, if this line is really not necessary.

**Comment by zaziemo** [comment]
closed thanks to @lisbethmarianne & @Powerglove :)
