### ISSUE TITLE
create popup for not-signed-in users if they want to submit an event

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#201]
as @ariaru requested in #190, we need a flash message that is neither green (success) or red (error) but just conveys information. I'd say blue!

**Comment by ariaru** [comment]
I think blue is good!
And maybe it can be a bit bigger so that it won't get mistaken to be insignificant.
Another way of handling this could be to make a whole separate view for this.
(?)

**Comment by lislis** [comment]
@ariaru maybe we should do a popup?

**Comment by ariaru** [comment]
Sounds good to me! :smile:

**Comment by lislis** [comment]
Sooooo, will you render the popup or do I need to figure out how to do that?

**Comment by lislis** [comment]
@ariaru can you describe the workflow you want to go with in here? Then we can start with the implementation

**Comment by lislis** [comment]
The thing: we have a class on the link now. --> create popup and display if class.
See this https://github.com/rubymonsters/diversity_ticketing/pull/190/commits/dc34c88c5563c06485a14f444d419d63aee96a4af

**Comment by lislis** [comment]
@ariaru do we have copy for the popup yet? Something like 
```
You're not signed in!
Create an account to submit an event to diveristytickets.org
```
Or something?

**Comment by lislis** [comment]
@ariaru can this be closed?

**Comment by lislis** [comment]
Closing!
