### ISSUE TITLE
Add logos to events

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#202]
Once #102 is merged, we can start putting the logos everywhere. In all the lists and other places.

**Comment by lisbethmarianne** [comment]
You can start this. 👍

**Comment by lislis** [comment]
I'd start with adding logos to the following views:
<img width="448" alt="screen shot 2016-07-18 at 19 26 47" src="https://cloud.githubusercontent.com/assets/1006478/16924124/ef167ce4-4d1d-11e6-8360-473be4352715.png">

<img width="518" alt="screen shot 2016-07-18 at 19 27 53" src="https://cloud.githubusercontent.com/assets/1006478/16924133/fc5dc178-4d1d-11e6-8f9e-a45aa21870f5.png">
