### ISSUE TITLE
Discuss: Time Zone for Deadline

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#204]
Anika: " ...if it would be okay with you to use UTC? my reasoning behind it would be to not be US-centric of EU-centric, but just use a timezone that has no attachment to any country "

At the moment we use Pacific Time (US & Canada)

**Comment by anikalindtner** [comment]
heja! any news on that? if there are no hard feelings, I'd love to just start using UTC. Having a US-based timezone for e.g. EU-based conferences probably confuses people a lot. And I think we can avoid that by simply using UTC, which is perfect for that. We also use UTC in other projects like Rails Girls Summer of Code and have had really good experiences with it. 

If there are no vetos until *this Friday, 17th of June*, let's change it to UTC! <3

**Comment by ariaru** [comment]
+1 for UTC :)

**Comment by anikalindtner** [comment]
okay, can someone take this on plz? it still says pacific time on the website. maybe @ariaru or @lisbethmarianne you'd have a minute today to fix it?
