### ISSUE TITLE
Past events list is missing styles

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#206]
The event list on route `/past_events` seems to be missing styles.

Is state:

<img width="1025" alt="screen shot 2016-05-23 at 19 50 09" src="https://cloud.githubusercontent.com/assets/1006478/15479254/9c8f0b1e-211f-11e6-8689-4623edf69184.png">

Should  state:
<img width="996" alt="screen shot 2016-05-23 at 19 50 17" src="https://cloud.githubusercontent.com/assets/1006478/15479259/a428353a-211f-11e6-9b47-60d4eb5dac39.png">

**Comment by bioshrimp** [comment]
done.
