### ISSUE TITLE
Underneath events whose application deadline has passed: show disabled "Apply" button instead of no button

### ISSUE THREAD

**Issue by Powerglove** [rubymonsters/diversity_ticketing#217]
line underneath disabled button saying "Applications closed"

**Comment by ariaru** [comment]
@bioshrimp @lislis 
This is what we were talking about last night, no? (...Better solution than the current no-button-at-all one, because less confusing...)
:)

**Comment by lislis** [comment]
@ariaru yisss!

**Comment by svenfuchs** [comment]
Maybe also add a message saying "Application deadline passed" or something? :)
