### ISSUE TITLE
Events Page when no events

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#222]
Front Porch Conference is soon (2016-07-19), after that it will move to the past events and the events page will be empty. Like this:

![bildschirmfoto 2016-07-12 um 10 56 15](https://cloud.githubusercontent.com/assets/11691539/16761175/4b7b9f36-481f-11e6-9622-bfa558aa93f1.png)

We should do something about that. 

Do we create another example event? Or display a message, that there are currently no events? What do you think @anikalindtner & @alicetragedy?

**Comment by anikalindtner** [comment]
@lisbethmarianne i'd be for adding a "New events will be coming soon! [Submit yours now.](LINK)" message.

**Comment by lislis** [comment]
I think the copy is a bit confusing from an UX perspective.
You come and expect a list of events and then you read 'new events will be coming soon' seems a little inconsistent.
I'd go for something like:
```
We currently have no events lined up.
But we'll add new ones soon!
You can submit yours now or look at old events.
```
Wdyt?

**Comment by lislis** [comment]
<img width="627" alt="screen shot 2016-07-18 at 20 00 11" src="https://cloud.githubusercontent.com/assets/1006478/16924982/494ada9e-4d22-11e6-87fd-6729af65feed.png">
Looks like this now

**Comment by lisbethmarianne** [comment]
I like it. 👍
