### ISSUE TITLE
DB backups

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#225]
We need them!

https://postgres.heroku.com/databases/diversity-tickets-production-database#snapshots

**Comment by mauditecandela** [comment]
I just scheduled a daily backup which is included in the heroku hobby-dev plan. It should run daily at 00:00 Berlin time. I want to wait until tomorrow to see if it worked properly. If yes, I will close this issue :)

**Comment by mauditecandela** [comment]
The backups work, we can close this issue. :)
