### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#237]
... at some point

**Comment by lisbethmarianne** [comment]
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html

**Comment by Powerglove** [comment]
better to upgrade Ruby first. Rails 5 needs 2.2.2 or newer, we are currently at 2.1.5

**Comment by ferbsx** [comment]
Started this today, using https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] Step 4
- [ ] Step 5
- [ ] Step 6
- [ ] Step 7
- [ ] Step 8
- [ ] Step 9

**Comment by mauditecandela** [comment]
Fixed by #330
