### ISSUE TITLE
send out reminder 48 hours day before deadline ends

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#240]
Would be great to get an email reminder (just like the notification that a new event has been submitted) that an application deadline ends 48 h before it does. This would allow some last-minute actions like informing the orga team, tweeting, spreading the word a bit more.

**Comment by Powerglove** [comment]
@anikalindtner Is this issue related to #235 ?

**Comment by lisbethmarianne** [comment]
@Powerglove I'd say yes.

**Comment by anikalindtner** [comment]
ah sorry, yes. closing this one now in favor of #235 but we should change 235 to 48-hours before, not 24.
