### ISSUE TITLE
Icon for (un-) approving events

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#245]
In the admin overview of events the `approve/ unapprove` action is the only one without an icon. (the others are edit and d.elete) 
It would be cool to have an icon there as well.

<img width="488" alt="screen shot 2016-08-22 at 19 46 48" src="https://cloud.githubusercontent.com/assets/1006478/17865143/5a1c8738-68a1-11e6-974d-d4f6700a12a7.png">

<img width="503" alt="screen shot 2016-08-22 at 19 48 19" src="https://cloud.githubusercontent.com/assets/1006478/17865157/692dbc06-68a1-11e6-8dab-303a94c76c12.png">

ping @saltinejustine

**Comment by saltinejustine** [comment]
@lislis how about something like this?

<img width="338" alt="screen shot 2016-09-07 at 12 44 10 pm" src="https://cloud.githubusercontent.com/assets/823381/18320668/d310a9e0-74f8-11e6-96ed-63e52491d558.png">

**Comment by lislis** [comment]
@saltinejustine sweet! I'm digging it 💃

**Comment by saltinejustine** [comment]
@lislis Supa. I've made two options. One with the status icon within a circle, and one without. IMO the icons with the circle are better, more well rounded icons, but I'll leave final decision up to you folks.

<img width="252" alt="screen shot 2016-09-07 at 3 52 16 pm" src="https://cloud.githubusercontent.com/assets/823381/18326382/72b7ca18-7513-11e6-9951-03081181e931.png">

💾 Files here —  [DT-Approve and Unapprove-Icons.zip](https://github.com/rubymonsters/diversity_ticketing/files/460209/DT-Approve.and.Unapprove-Icons.zip)

**Comment by lislis** [comment]
PR was merged here https://github.com/rubymonsters/diversity_ticketing/pull/254
