### ISSUE TITLE
Ideas for Prototype Fund application

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#250]
New features:
- If this turns out to be a requirement: translate the whole site to German
- Tagging functionality for events (place, technology/language/topic, ...)
- Subscription functionality for events with certain tags
- (Optional) user accounts for applicants
- Diversity-in-tech initiatives can also (have user accounts and) subscribe to notifications, so that they can spread the news about events
- Dashboards for event organizers and applicants

Deadline for application: Sept 30th
Our internal deadline (and possible meeting with Anika): Sept 26th

**Comment by lisbethmarianne** [comment]
Application sent. Closing this. 🙌
