### ISSUE TITLE
Build export functionality

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#26]
- DB contents --> CSV file, e.g. all applications per event
- Add a link to download the CSV file

**Comment by zaziemo** [comment]
we thought about adding the button in the admin index view as sketched in #2

**Comment by joecorcoran** [comment]
Some useful links:

* http://ruby-doc.org/stdlib-2.1.5/libdoc/csv/rdoc/CSV.html
* http://railscasts.com/episodes/362-exporting-csv-and-excel?view=asciicast

**Comment by joecorcoran** [comment]
Tasks:

* [ ] Write a method on the `Event` class that returns a CSV containing all the event's applications

**Comment by joecorcoran** [comment]
Extracting values from a record. Hints!

* http://apidock.com/rails/ActiveRecord/AttributeMethods/attributes
* http://ruby-doc.org/core-2.1.5/Array.html#method-i-slice
