### ISSUE TITLE
Email notification for new events

### ISSUE THREAD

**Issue by szabgab** [rubymonsters/diversity_ticketing#260]
Is there a way to get e-mail notification when a new event appears?
If not yet, let this be a feature request.

**Comment by Powerglove** [comment]
@szabgab We will look into it soon :)

**Comment by guainumbi** [comment]
@szabgab / @Powerglove there is a new feature now that lets you add fields of interest to your private profile if you signed up with a user account. You can add in your "account settings" that you wish to be notified when new events are being released that match your fields of interest and/or take place in the country you've selected in your account. :) (closing this issue as the feature has been added)
