### ISSUE TITLE
Internationalization - French translation

### ISSUE THREAD

**Issue by AmauryVanEspen** [rubymonsters/diversity_ticketing#277]
Hi,

I would like to support your initiative by translating your project,
would you be kind to let me know how to setup a language file system ?

Best

Amaury

**Comment by anikalindtner** [comment]
Hi @AmauryVanEspen! Thank you so much for reaching out and wanting to support our project! Unfortunately we don't yet have the resources to support translations and implement them for more languages. It is something we do consider for the future though! 

So I'd love to come back to you once we've figured out how to proceed from where we are and who could take responsibility on this from our side. 

Thank you so much again for your PR, I'll close this issue for now and will ping you again at a later time if that is okay with you.

**Comment by borisschapira** [comment]
If you decide to implement i18n one day, I will be happy to provide my help for a fr_FR translastion.

**Comment by mauditecandela** [comment]
@borisschapira + @AmauryVanEspen + @anikalindtner I18n has been implemented, so now FR translations are open! Here there's some guidance, although you may not need it :) https://github.com/rubymonsters/diversity_ticketing/wiki/Do-you-want-to-translate-Diversity-Tickets-to-your-own-language%3F-Here-are-some-indications:

**Comment by borisschapira** [comment]
@AmauryVanEspen + @anikalindtner 	I've proposed a translation, if you want to readproff it. https://github.com/rubymonsters/diversity_ticketing/pull/470 (thanks @mauditecandela, it took some time starting, but I did it ^^).

**Comment by AmauryVanEspen** [comment]
Hi,

I'm gonna read it this weekend

Thanks

Amaury

**Comment by borisschapira** [comment]
PR has been merged (https://github.com/rubymonsters/diversity_ticketing/pull/470) so I guess the issue can be closed, except if @lislis wants to keep it open until she adds the missing ES translations before a release.

If you have new strings to translate, please feel free to @ me.

**Comment by lislis** [comment]
It is live! https://diversitytickets.org/fr
Thank you for all the work @borisschapira

**Comment by alicetragedy** [comment]
![dancing-panda-small](https://user-images.githubusercontent.com/3143348/55728976-86916780-5a15-11e9-9cbb-9af68795c244.gif)
