### ISSUE TITLE
The "twitter" field in the event editor not persisted

### ISSUE THREAD

**Issue by flaki** [rubymonsters/diversity_ticketing#283]
The value of the `twitter` field in the event editor is not saved when the form is submitted, no error is shown.

**Comment by anikalindtner** [comment]
ah this could explain why the tweets go out without the twitter handle of the conferences!

**Comment by anikalindtner** [comment]
So for all events it just looks like this now: 

<img width="465" alt="screen shot 2017-05-10 at 12 33 18" src="https://cloud.githubusercontent.com/assets/1711357/25894826/bd15bd88-357d-11e7-9031-d687f44e81a2.png">

Even though they put in their real twitter handle. And it can't even be edited by admin afterwards.
