### ISSUE TITLE
admin view broken when email too long

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#284]
When looking through the applicants, this happens when the email / the name is too long: 

<img width="458" alt="screen shot 2017-05-08 at 09 26 44" src="https://cloud.githubusercontent.com/assets/1711357/25814378/9ac2cfca-341d-11e7-8ef4-c5c554943ce1.png">

Would be nice if it all was in one line. I'm also happy to just get the "old" design back with the one column. That made things in the admin view way easier for me to navigate :)

**Comment by lisbethmarianne** [comment]
I hope that's solved, let me know if not.
