### ISSUE TITLE
add notifications of event deadline passed

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#285]
Would it be possible to add a notification for a deadline that just passed - but only for conferences that we are handling? ( not the ones that are just listings?)

I imagine an email like the one we get for if the deadline is 2 days away. This would make it a lot easier to have an overview which conf we have to send the list of selected winners. 

Could be just a quick notification like: 

"Dear Admin, the deadline for conf X has passed. Click here to select the winners: link/event/admin". 

Preferably just minutes after the deadline has passed. Is this possible?

**Comment by bitboxer** [comment]
@anikalindtner I am now working on the mail, but I have no idea about the timing. I am now copying the deadline passed stuff and write something that sends mails for events where the deadline was yesterday. The deadline can only be a date, not a time when I understood correctly. And I have no clue how the deadline stuff is executed. There must be a cron configured somewhere 😉

**Comment by lisbethmarianne** [comment]
Just realized we don't filter out the events that are just listings. 

I like that this email has a link to the admin event view, we should also include this in the other admin mails.

Will make a PR for this.
