### ISSUE TITLE
Create text for FAQs where we explain how to get a new tag that is currently not in the tags list

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#302]
When making a new event an organizer can select from a list of existing tags but they can not create  a new tag. They have to request this (via email) and the admin can then create it for them if they thing this tag makes sense.

There will be a link in the new event page that links to this description on the faq page.

PR for Tags: #261

**Comment by alicetragedy** [comment]
added in https://github.com/rubymonsters/diversity_ticketing/pull/261/commits/5e59a518f4a3c7306b8be030896c8838e7f2bdd1 so I think we can close this? (cc @lisbethmarianne )
