### ISSUE TITLE
Event Submitted email improvements

### ISSUE THREAD

**Issue by MariadeAnton** [rubymonsters/diversity_ticketing#311]
It would be great that as part of the email sent out on the application, we could send the following details in the email "A new event has been submitted."

Effectively adding the following details to the email: 

- Submitter Name 
- Submitter Email
- Kind of application

What do you think? Thank you!

**Comment by alicetragedy** [comment]
Some background for this request (cc @lisbethmarianne): 
Maria was helping to reply to incoming requests while I was on holiday, and she pointed out that it might make the general workflow easier if we have this information in the email, particularly the kind of application.

What do you think?
