### ISSUE TITLE
Open graph tags for Event Detail Page

### ISSUE THREAD

**Issue by mauditecandela** [rubymonsters/diversity_ticketing#328]
We have the same open graph tags accross the website. In order to have a better visibility in Facebook, we should have specific open graph tags in events, so the name and the description of the event is present. 

<img width="651" alt="captura de pantalla 2018-04-11 a las 10 03 35" src="https://user-images.githubusercontent.com/8235980/38604143-c9e1a946-3d6f-11e8-87f8-076c83a542b4.png">
Current implementation. 

Proposal for events details pages open graphs (something like:)

```
<meta property="og:description" content="Diversity Tickets | <%= @event.description %>">
<meta property="og:image" content="<%= "#{root_url}assets/event-default.png" %>">
<meta property="og:title" content="We help events reach a more diverse audience. And we help you to find these events.">
<meta property="og:site_name" content="<%= @event.name %> | Diversity Tickets">
<meta property="og:url" content="https://diversitytickets.org/">
<meta property="og:type" content="website" />
```

**Comment by mauditecandela** [comment]
Related issue: The image tag shows a warning in the facebook debugger: 
<img width="1016" alt="captura de pantalla 2018-04-11 a las 11 02 35" src="https://user-images.githubusercontent.com/8235980/38607019-edb6b9c6-3d77-11e8-984b-f217759f1fe5.png">

**Comment by lisbethmarianne** [comment]
This line is broken `<meta property="og:image" content="<%= "#{root_url}assets/event-default.png" %>">` and needs to be fixed. We might have to use sth like `<%= asset_path 'image.png' %>`.
