### ISSUE TITLE
Split FAQ list into sections

### ISSUE THREAD

**Issue by alicetragedy** [rubymonsters/diversity_ticketing#342]
The content of the FAQ page has been split into different sections (“General”, “For conference organisers”, etc.) which is great! A possible enhancement would be to basically add those headings to the list with the anchor links at the top of the page, to give people a quick overview there as well (see screenshot for what I mean by “list”).

<img width="1143" alt="screen shot 2018-05-15 at 11 28 18" src="https://user-images.githubusercontent.com/3143348/40048697-21727c98-5833-11e8-8d7c-d1801ce1cb76.png">

I think this is a fairly non-complex task that doesn't require much expertise in Ruby but rather some limited knowledge of HTML so it would make for a good beginner-friendly issue :)

**Comment by guainumbi** [comment]
@drashti4 please feel free to work on it. I can not assign you to this issue but you can just fork it and create a pull request when you are done.
