### ISSUE TITLE
Typo error?

### ISSUE THREAD

**Issue by drashti4** [rubymonsters/diversity_ticketing#368]
Hi there, I seen in footer of website there's powere by "RubyMonstas", Is it German word or it should be "RubyMonsters"?

**Comment by alicetragedy** [comment]
Hi @drashti4, thank you for submitting this issue! The group is in fact called “RubyMonstas” ([link](http://rubymonstas.org/)) so it's not a typo :)
I'm going to close this issue now, but feel free to open more if you find any errors across the site. Thanks 🎉
