### ISSUE TITLE
First version of organizer application web form

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#4]
- Routes
- Controller
- View

**Comment by lisbethmarianne** [comment]
I'm trying to work on this one. I'm making a new branch. I might not work out things the right way, just want to do something. ;P

**Comment by lisbethmarianne** [comment]
Is there a possibility to put the date (which is probably more than one day) in just one form field or do we have to split into starting_date and ending_date? Not sure how to do this.

**Comment by lisbethmarianne** [comment]
I opened a pull request #8. Someone can look at it (and merge or don't merge). I basically followed the instructions here: http://guides.rubyonrails.org/getting_started.html (points 5.1 - 5.9, without 5.4 and 5.5).

**Comment by lisbethmarianne** [comment]
I fixed the date problem, see pull request #10 
2 migrations: added an end_date + changed column date to start_date
changed views accordingly (new, show)
changed permit parameters in events_controller

We probably need validations...?
