### ISSUE TITLE
State event title in page title

### ISSUE THREAD

**Issue by jancborchardt** [rubymonsters/diversity_ticketing#409]
Currently the page title is always "DiversityTickets". That makes it very difficult to find pages from history (for example). Better would be to include the current page description before the general project title like:

- Submit event – Diversity Tickets
- Events – Diversity Tickets
- EuRuKo 2018 – Diversity Tickets
- Nextcloud Conference – Diversity Tickets
- About – Diversity Tickets

And so on. :)

**Comment by guainumbi** [comment]
yes, that is a good point. we can probably address this together with the personalized og tags that are on our list. :)

**Comment by jancborchardt** [comment]
Good stuff! :) Thanks @siaw23 for the fix!
