### ISSUE TITLE
Add fields to events table

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#41]
- ~~deadline 4 submission~~
- ~~field where the organizers can type how many tickets they are giving~~
- ~~venue of the conference~~ (later: show conferences near me)
- ~~Link to homepage~~
- ~~Link to the code of conduct~~
- ~~what is funded? travel, accomodation, ???~~
- description of the application process
- should we leave out questions? Organizers shouldn't have any say, just dietary info or  t-shirts size---- think about it. Or optional maybe. They shouldn't be able to ask sensitive stuff. Rephrase: extra info ... like t-shirts and stuff.

**Comment by Powerglove** [comment]
Add link to the Code of Conduct

**Comment by lisbethmarianne** [comment]
Maybe something like this? https://form.jotformeu.com/52822997388373

**Comment by lisbethmarianne** [comment]
Anikas feedback on the last 2 points: 
"Description of the application process brauchen wir nicht"

Extra info: T-Shirt ...
"ja das hatte ich überlegt, aber andererseits kann das dann auch eigentlich die Konferenz selbst mit den Gewinner_innen auskaspern. Ich würd das also erstmal weglassen, ebenso wie dietary information etc. Letztendlich kriegen sie ja von uns eine Email mit den Namen der Leute und die müssen sich ja dann meistens eh nochmal über einen link für ihr Ticket anmelden."


What is missing is a logo upload field see also #46

**Comment by fidothe** [comment]
fixed in #80
