### ISSUE TITLE
The page you were looking for doesn't exist.

### ISSUE THREAD

**Issue by siaw23** [rubymonsters/diversity_ticketing#410]
I'm getting this error while trying to login with email and password:

<img width="638" alt="screen shot 2018-07-30 at 00 11 38" src="https://user-images.githubusercontent.com/4806407/43371194-5bfc6d2a-938d-11e8-9bf0-a64a31ab9320.png">

On this URL: https://diversitytickets.org/users

**Comment by guainumbi** [comment]
hi @siaw23 , that's because it indeed does not exist :) The URL you're looking for is: https://diversitytickets.org/sign_in 

(closing this issue as not related)
