### ISSUE TITLE
Implement the use of tags for event organizers

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/diversity_ticketing#43]
- Is it cool to have tags like "ruby conferences" or other types of conferences, so people can sort

-> we have to think whether it is good to use a gem like acts-as-taggable for that

**Comment by Powerglove** [comment]
- [ ]  create Tag resource (showing list of events with certain tag, show list of tags)

- [ ] create Tagging model 

- [ ] show tags in event view and in event list

- [ ] update create event form

**Comment by lisbethmarianne** [comment]
![tags3](https://cloud.githubusercontent.com/assets/11691539/20498755/9b4d81e2-b02e-11e6-9ca2-b95c0a5661b6.png)
![tags4](https://cloud.githubusercontent.com/assets/11691539/20498756/9b4dd52a-b02e-11e6-8e89-9c52c1fa8297.png)
![tags2](https://cloud.githubusercontent.com/assets/11691539/20498753/9b49b30a-b02e-11e6-8ac1-c8ae3dd8e9b6.png)
![tags1](https://cloud.githubusercontent.com/assets/11691539/20498754/9b4b654c-b02e-11e6-8834-013cb066586e.png)

**Comment by mauditecandela** [comment]
Fixed by #261
