### ISSUE TITLE
"Field of Interest" tags don't have a background color

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#438]
<img width="493" alt="screen shot 2018-08-25 at 08 25 52" src="https://user-images.githubusercontent.com/11691539/44615713-2f050980-a841-11e8-9bbb-cb2aac79edd9.png">

Like "English" the other tags should have also a color.

**Comment by guainumbi** [comment]
Has been fixed in staging and will be part of the next deployment to production. :)

**Comment by lisbethmarianne** [comment]
@guainumbi When will this happen?
I don't fully understand your process, but I think you are accumulating features and then release them once a month or so. Right?

I think this is a bug and should be fixed as soon as possible. (In my opinion.)

**Comment by guainumbi** [comment]
@lisbethmarianne I will make the deployment tomorrow. :) I was planning on deploying to production today but it is a fairly big review that I did not want to rush as I am reviewing the PRs alone this week and didn't want to risk any follow up bugs.

Yes, in general we are deploying to staging first, so we can collect feedback and when everything is fine we merge to master and deploy to production from there. However, quick bug fixes can be merged directly to master.
