### ISSUE TITLE
Filter events by theme/location

### ISSUE THREAD

**Issue by vsmart** [rubymonsters/diversity_ticketing#442]
There are so many events listed on diversitytickets now! That is very exciting and a great sign of adoption and success for this page 🎉 

It would be great to have a `filter` option at the top of the page to get a faster overview. 

I could imagine: 

- filter by country / continent
- by topic

This could probably be integrated with the `tags` you have listed under each event.

Thanks for your great work 🙇‍♀️ ✨

**Comment by guainumbi** [comment]
Thank you @vsmart ! You're right, that's so exciting
