### ISSUE TITLE
Rendering issue in Firefox

### ISSUE THREAD

**Issue by shubheksha** [rubymonsters/diversity_ticketing#459]
Please refer to the screenshot
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/7693422/46863626-38116080-ce18-11e8-86a1-08b9684513ed.png">
A few elements overlap affecting readability. 
Page: https://diversitytickets.org/en/events

**Comment by cfleschhut** [comment]
Fixed & deployed w/ https://github.com/rubymonsters/diversity_ticketing/pull/462

**Comment by shubheksha** [comment]
Closing the issue, thanks!
