### ISSUE TITLE
Add Picture/Logo for event

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#46]
- make it possible for an organizer to add a picture or logo
- placeholder picture if no picture is uploaded

**Comment by lisbethmarianne** [comment]
https://github.com/carrierwaveuploader/carrierwave

**Comment by lisbethmarianne** [comment]
Carrierwave is a bad idea, doen't work with Heroku!!!!!

**Comment by sabrina-ulbrich** [comment]
There is a way to make them work together with an external space for the pictures: https://aws.amazon.com/de/s3/
see here:
https://github.com/carrierwaveuploader/carrierwave/wiki/how-to%3A-make-carrierwave-work-on-heroku

speakerinnen use this, but I am not sure whether this is the best or simplest way.

**Comment by lisbethmarianne** [comment]
Uploading Event/Conference Logos: Should we restrict people to certain image types (jp(e)g/png) and image size (pixel, mb)?
