### ISSUE TITLE
add link to csv download to event admin page 

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#463]
it would be great if we could add a download-button for the single event page here:
<img width="542" alt="screen shot 2018-11-19 at 12 00 07" src="https://user-images.githubusercontent.com/1711357/48703055-e0260080-ebf2-11e8-89f2-ed8f54d5699a.png">

https://diversitytickets.org/en/events/EVENT_ID/admin

This would save me a lot of time, meaning that i don't have to leave that events-admin-page and go to the overview (https://diversitytickets.org/en/admin), look for the event and to download the .csv file.

**Comment by lislis** [comment]
Done in #474 Thank you!
