### ISSUE TITLE
The `pluralize` helper (in views) does not work in FR and ES

### ISSUE THREAD

**Issue by borisschapira** [rubymonsters/diversity_ticketing#476]
```
<%= pluralize(@event.number_of_tickets, t('.ticket')) %>
```

does pluralize in English but not in French or Spanish.

**Comment by lislis** [comment]
True! Here the rails guides section with a solution https://guides.rubyonrails.org/i18n.html#pluralization

**Comment by borisschapira** [comment]
Oh, I think the issue isn't, therefore, that `pluralize` does not support French or Spanish but that it need a locale to apply the right rule, like `fr-FR` or `es-ES`… I'll try something.

**Comment by borisschapira** [comment]
Ok, was way more simpler than that :D At least I think so. I'm a bit of a Ruby beginner, but I think I found it.
