### ISSUE TITLE
New index views for past events (Admin page)

### ISSUE THREAD

**Issue by guainumbi** [rubymonsters/diversity_ticketing#487]
I noticed that we accumulated a LOT of past events 😊🏆🎉 (past approved as well as past unapproved) and it seems to affect the loading time for admin event. might be caused by something else, too but it definitely does "clutter" the view. My suggestion would be a separate index view for past unnaproved events and past approved events that can be linked to the admin_events_index view? We could also show the most recent (e.g. 10) past approved events for convenience. what do you think? @anikalindtner @alicetragedy

**Comment by lisbethmarianne** [comment]
I will take this one and also separate the statistics/reports to it's own view.
