### ISSUE TITLE
Update ES translation for searchbar placeholder text

### ISSUE THREAD

**Issue by guainumbi** [rubymonsters/diversity_ticketing#500]
The ES translation locales need to be updated to fit the english transcription of our searchbar input field placeholder. ( "location" has been added for descriptiveness & UX-improvement).

You need to update the existing string in
events:
  event_search:
     enter_search:

**Comment by albertojauregui** [comment]
Solution on the next PR https://github.com/rubymonsters/diversity_ticketing/pull/519
