### ISSUE TITLE
How to: description of the application process

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/diversity_ticketing#52]
Describe the application process for the 
a) organizer
b) applicant

Idea: add an FAQ section

**Comment by anikalindtner** [comment]
@zaziemo how would you like this to be? should I write up a text which you then transform into documentation or FAQ? Or should I just write the FAQ? Or would it be more helpful if we add inline documentation (with a little "?"-sign or sth that people can click on)?

**Comment by lisbethmarianne** [comment]
@anikalindtner 
Some general information should be on the home page https://tranquil-lake-9560.herokuapp.com/

a) If necessary we could include a litte text for organizers here: https://tranquil-lake-9560.herokuapp.com/events/new

b) There should be some information for the applicants here (or a link to FAQs) https://tranquil-lake-9560.herokuapp.com/events/2/applications/new, so they know what is going to happen, who can apply who not, how is the selection process (lottery). Not sure if this is different for every event, then we have to include it in the form for the organizer (new event).

If you write some texts/FAQs, we can figure out where to add them.

**Comment by sabrina-ulbrich** [comment]
the links doesn’t work anymore, use instead:

https://diversity-tickets-production.herokuapp.com/

and

https://diversity-tickets-production.herokuapp.com/events/new

and

https://diversity-tickets-production.herokuapp.com/events/2/applications/new


Sabrina

**Comment by fidothe** [comment]
@anikalindtner any updates on this?

**Comment by alicetragedy** [comment]
@fidothe I've volunteered to draft up something for the FAQ/About page (see discussion here: https://github.com/rubymonsters/diversity_ticketing/issues/117); I think we can easily keep most of the info there :)

**Comment by anikalindtner** [comment]
awesome, laura! :sparkles:
