### ISSUE TITLE
Notification to organizer after submitting new event

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#60]
- show information to the organizer after they submitted the event
- Annika will send the text

Info: The eventis not visisble until it is approved.

see also #59

**Comment by anikalindtner** [comment]
Hey @lisbethmarianne what kind of text do you need from me here? The notification that says "your event has been submitted"? Or the email itself?

**Comment by lisbethmarianne** [comment]
@anikalindtner I think we said there should be some information for the organizer, what the process is after submitting an event. This could be on the page that shows after the submit button is clicked or via email (via email is maybe the best) I.e. that the event is not visible yet, it first has to be approved by the admin. 

We could write:
"Thank you for submitting your event <event-name>. 
Your event is not yet visible to the public. You will be informed as soon as your event is approved. 
<link to webpage>"

Not sure if the organizer needs more information. What do you think?

**Comment by anikalindtner** [comment]
@lisbethmarianne sounds perfect! 

I would just add one sentence more about: "If you have any more questions, please read the FAQ (link to FAQ). If you need more help, contact foundation@travis-ci.org."

**Comment by fidothe** [comment]
Fixed in #59
