### ISSUE TITLE
Decide on domain name

### ISSUE THREAD

**Issue by joecorcoran** [rubymonsters/diversity_ticketing#67]
Will we use an existing domain (e.g. something.rubymonstas.org, foundation.travis-ci.org/something)? Or do we need to purchase a new domain and if so, what will it be? Here's a nice tool for checking availability: http://domainr.com/

**Comment by anikalindtner** [comment]
I'd be up for purchasing a new domain which we then also can use to send emails from. So for example diversitytickets.org. I'll see that I can get this done asap. Any ideas on the name?

**Comment by joecorcoran** [comment]
There are some new TLDs we could possibly take advantage of, like `.tickets` and `.events`.

I notice, for example, that `diverse.events` is [available](https://domainr.com/?q=diverse+events)...

**Comment by anikalindtner** [comment]
sounds also good! :+1: from me for this name

**Comment by anikalindtner** [comment]
@alicetragedy any ideas/comments regarding the name?

**Comment by alicetragedy** [comment]
I like the idea of both `diverse.events` and `diversity.tickets`. They're both available, I also [checked the latter](https://domainr.com/?q=diversity+tickets). :)

**Comment by anikalindtner** [comment]
@alicetragedy I've checked with konstantin - the .tickets thing you need to "apply" for. and i think they only want like trains and whatnot on this domains. diverse.events i like as well, but maybe the old but good diversitytickets.org?

**Comment by alicetragedy** [comment]
@anikalindtner ah okay, makes sense. If `diverse.events` is not possible and/or you're not sure about (especially because of costs), I think `diversitytickets.org` would be a great compromise. :+1:

**Comment by lisbethmarianne** [comment]
diversitytickets.org it is. :)
