### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#7]
As soon as possible! :)

**Comment by Powerglove** [comment]
I tried to deploy our app to Heroku and I think it worked. Maybe you can have a look at it tonight? Did the deployment work or is anything still missing?

**Comment by sabrina-ulbrich** [comment]
What's the link and the name of the application (diversity_ticketing)?

**Comment by Powerglove** [comment]
good question, I hope this works:

https://tranquil-lake-9560.herokuapp.com/

Or do I need to add all of you as collaborators?

**Comment by kaeptnjules** [comment]
Hey Johanna,

hier ist Jule. Schickst du mir bitte mal auch noch so eine Einladung?!

Danke!

**Comment by Powerglove** [comment]
Hey, who else needs an invitation? I just need your mail address! :)

**Comment by sabrina-ulbrich** [comment]
This link https://tranquil-lake-9560.herokuapp.com/ doesn't work for me and Jule, don't know why, but the error message is: The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved.

**Comment by Powerglove** [comment]
Ok, I am trying to install the Toolbelt and create a new public SSH public key. Maybe that helps

**Comment by joecorcoran** [comment]
Seems like these are the steps for Heroku deployment (let's try it on everyone's machines):

1. Install https://toolbelt.heroku.com/
2. `heroku login` (enter your Heroku login details)
3. `heroku git:remote -a tranquil-lake-9560`
4. `git push heroku master`
