### ISSUE TITLE
design of the app

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/diversity_ticketing#9]
@bioshrimp if you want, you can start with that and be creative :) Probably you want to talk to Anika about her wishes.

**Comment by lisbethmarianne** [comment]
Hej, I'm getting sick of seeing these white pages with some boxes and text. If you need help with this let me know. I am not a designer, so you should probably do some sketches in Photoshop (or however this works), but I'd be happy to improve my HTML/CSS knowledge. :)

**Comment by ariaru** [comment]
@lisbethmarianne and everyone else, if you want to learn some (more) CSS, this might be a good opportunity (be quick, not many free spots left): http://www.meetup.com/de/opentechschool-berlin/events/225073641/?eventId=225073641&a=co2_grp&gj=co2&rv=co2&chapter_analytics_code=UA-33344154-1&rv=co2

**Comment by zaziemo** [comment]
we should have a basic design before we show it to Anika.

**Comment by zaziemo** [comment]
I talked to Anika, she ideally wants it in the design of the Travis Foundation sites and will ask their own webdesigner if she has time to do it. For us it means that we shouldn't add anything complicated - probably nothing than structure untill she gives us an answer on that.
