### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#90]
put some useful information in the Readme 
https://en.wikipedia.org/wiki/README

**Comment by lisbethmarianne** [comment]
See #100. @ferbsx feel free to add some more info.

**Comment by ferbsx** [comment]
Definitely will :D

**Comment by alicetragedy** [comment]
:+1: 

Would be nice to have some infos on getting up and running quickly, for people who want to contribute :)

**Comment by ferbsx** [comment]
Don't forget to add Code of Conduct for contributing.

**Comment by lisbethmarianne** [comment]
Looks like this is done, thank for the hard work @ferbsx
