### ISSUE TITLE
Add a real description to the home page

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/diversity_ticketing#96]
![screen shot 2015-11-24 at 1 02 17 am](https://cloud.githubusercontent.com/assets/11502220/11353850/2b52c2f4-9247-11e5-95cc-a58f7ae5075c.png)

**Comment by lisbethmarianne** [comment]
![image](https://cloud.githubusercontent.com/assets/11691539/11977218/05bf4bce-a981-11e5-86e4-d7988af8bb31.png)

@anikalindtner Can we use this text?

**Comment by alicetragedy** [comment]
@lisbethmarianne I think it sounds pretty good :+1: 
**Note**: I would just change “An app to help your events reach a more diverse audience” to "An app to help events reach a more diverse audience” (remove the “your”) as I see the app as being beneficial to attendees as well. “your events” makes it sound like it’s directed at event organisers only. (I know it mostly is, however attendees benefit from it, too – by applying).

**Comment by svenfuchs** [comment]
I think @alicetragedy has an important point. I also feel that "An app" kinda looses the opportunity to help users identify with "us". It's not some anonymous app that helps, it's "us", isn't it?

> We help events reach a more diverse audience.

However, thinking more about what @alicetragedy said, I still feel this mostly targets event organizers.

> We help events reach a more diverse audience. And we help **you** to find these events.

Probably does not fit on one line with the given font size, I guess?

WDYT?

**Comment by svenfuchs** [comment]
@lisbethmarianne btw ... no matter what comes out of this discussion, I think you (as in, the group) can already work on implementing this. A few words can always be updated later, too :)

**Comment by fidothe** [comment]
closed by #113.
